AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FishTrackerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: FishTrackerLambdaAnnotated::FishTrackerLambda.Functions_GetTrips_Generated::GetTrips
      Runtime: dotnet8
      CodeUri: ./src/FishTrackerLambdaAnnotated
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: Development
          AWS_SAM_LOCAL_LOG_LEVEL: debug
      Events:
        GetTrips:
          Type: Api
          Properties:
            Path: /api/trip
            Method: get
            RestApiId:
              Ref: ApiGatewayRestApi
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: FishTrackerApi
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Cookies'"
        AllowOrigin: "'*'"
