# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore: master    
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FishTrackerLambda

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # - name: Debug output
      #   run: ls src/FishTrackerLambda/bin/Debug/net6.0
      # - name: Create output
      #   run: mkdir output
      # - name: Create lambda-deploymentpackage.zip
      #   run: zip -r -j output/lambda-deploymentpackage.zip src/FishTrackerLambda/bin/Debug/net6.0/*
      # - name: Current Directory
      #   run: pwd
      # - name: contents Current Directory
      #   run: ls
      # - name: Debug output
      #   run: ls output

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14
  
      # - name: Install dependencies
      #   run: npm install
      #   working-directory: web
  
      # - name: Run tests
      #   run: npm run test:headless
      #   working-directory: web

          